<?php

return [
    '/' => ['controller' => 'HomeController', 'action' => 'index', 'method' => 'GET'],
    '/home' => ['controller' => 'HomeController', 'action' => 'index', 'method' => 'GET'],
    '/courses/{id}' => ['controller' => 'CourseController', 'action' => 'show', 'method' => 'GET'],
    '/courses/{id}/files' => ['controller' => 'CourseController', 'action' => 'files', 'method' => 'GET'],
    '/courses/{id}/rate' => ['controller' => 'CourseController', 'action' => 'rate', 'method' => 'POST'],
    '/announcements' => ['controller' => 'AnnouncementController', 'action' => 'index', 'method' => 'GET'],
    '/announcements/{id}' => ['controller' => 'AnnouncementController', 'action' => 'show', 'method' => 'GET'],
    '/search' => ['controller' => 'SearchController', 'action' => 'index', 'method' => 'GET'],
    '/about' => ['controller' => 'PageController', 'action' => 'about', 'method' => 'GET'],
    '/contact' => ['controller' => 'PageController', 'action' => 'contact', 'method' => 'GET'],
    '/majors/{id}' => ['controller' => 'MajorController', 'action' => 'show', 'method' => 'GET'],
    '/files/{id}/download' => ['controller' => 'FileController', 'action' => 'download', 'method' => 'GET'],
    '/files/{id}/preview' => ['controller' => 'FileController', 'action' => 'preview', 'method' => 'GET'],

    '/login' => ['controller' => 'AuthController', 'action' => 'loginForm', 'method' => 'GET'],
    '/login/post' => ['controller' => 'AuthController', 'action' => 'login', 'method' => 'POST'],
    '/register' => ['controller' => 'AuthController', 'action' => 'registerForm', 'method' => 'GET'],
    '/register/post' => ['controller' => 'AuthController', 'action' => 'register', 'method' => 'POST'],
    '/auth/google' => ['controller' => 'AuthController', 'action' => 'googleRedirect', 'method' => 'GET'],
    '/auth/google/callback' => ['controller' => 'AuthController', 'action' => 'googleCallback', 'method' => 'GET'],
    '/logout' => ['controller' => 'AuthController', 'action' => 'logout', 'method' => 'GET'],

    '/request-role' => ['controller' => 'JoinRequestController', 'action' => 'requestForm', 'method' => 'GET'],
    '/request-role/post' => ['controller' => 'JoinRequestController', 'action' => 'submitRequest', 'method' => 'POST'],
    '/pending-approval' => ['controller' => 'JoinRequestController', 'action' => 'pendingApproval', 'method' => 'GET'],

    '/admin/requests' => ['controller' => 'JoinRequestController', 'action' => 'adminIndex', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],
    '/admin/requests/{id}/approve' => ['controller' => 'JoinRequestController', 'action' => 'approve', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],
    '/admin/requests/{id}/reject' => ['controller' => 'JoinRequestController', 'action' => 'reject', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],

    '/admin' => ['controller' => 'DashboardController', 'action' => 'index', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/dashboard' => ['controller' => 'DashboardController', 'action' => 'index', 'method' => 'GET', 'middleware' => ['Auth']],

    '/admin/majors' => ['controller' => 'MajorController', 'action' => 'index', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/majors/create' => ['controller' => 'MajorController', 'action' => 'create', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],
    '/admin/majors/store' => ['controller' => 'MajorController', 'action' => 'store', 'method' => 'POST', 'middleware' => ['Auth', 'Admin']],
    '/admin/majors/{id}/edit' => ['controller' => 'MajorController', 'action' => 'edit', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],
    '/admin/majors/{id}/update' => ['controller' => 'MajorController', 'action' => 'update', 'method' => 'POST', 'middleware' => ['Auth', 'Admin']],
    '/admin/majors/{id}/delete' => ['controller' => 'MajorController', 'action' => 'delete', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],

    '/admin/levels' => ['controller' => 'LevelController', 'action' => 'index', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/levels/create' => ['controller' => 'LevelController', 'action' => 'create', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],
    '/admin/levels/store' => ['controller' => 'LevelController', 'action' => 'store', 'method' => 'POST', 'middleware' => ['Auth', 'Admin']],
    '/admin/levels/{id}/edit' => ['controller' => 'LevelController', 'action' => 'edit', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],
    '/admin/levels/{id}/update' => ['controller' => 'LevelController', 'action' => 'update', 'method' => 'POST', 'middleware' => ['Auth', 'Admin']],
'/admin/levels/{id}/delete' => ['controller' => 'LevelController', 'action' => 'delete', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],
    '/admin/semesters' => ['controller' => 'SemesterController', 'action' => 'index', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/semesters/create' => ['controller' => 'SemesterController', 'action' => 'create', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],
    '/admin/semesters/store' => ['controller' => 'SemesterController', 'action' => 'store', 'method' => 'POST', 'middleware' => ['Auth', 'Admin']],
    '/admin/semesters/{id}/edit' => ['controller' => 'SemesterController', 'action' => 'edit', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],
    '/admin/semesters/{id}/update' => ['controller' => 'SemesterController', 'action' => 'update', 'method' => 'POST', 'middleware' => ['Auth', 'Admin']],
    '/admin/semesters/{id}/delete' => ['controller' => 'SemesterController', 'action' => 'delete', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],

    '/admin/courses' => ['controller' => 'CourseController', 'action' => 'adminIndex', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/courses/create' => ['controller' => 'CourseController', 'action' => 'create', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/courses/store' => ['controller' => 'CourseController', 'action' => 'store', 'method' => 'POST', 'middleware' => ['Auth']],
    '/admin/courses/{id}/edit' => ['controller' => 'CourseController', 'action' => 'edit', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/courses/{id}/update' => ['controller' => 'CourseController', 'action' => 'update', 'method' => 'POST', 'middleware' => ['Auth']],
    '/admin/courses/{id}/delete' => ['controller' => 'CourseController', 'action' => 'delete', 'method' => 'GET', 'middleware' => ['Auth']],

    '/admin/files' => ['controller' => 'FileController', 'action' => 'index', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/files/create' => ['controller' => 'FileController', 'action' => 'create', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/files/store' => ['controller' => 'FileController', 'action' => 'store', 'method' => 'POST', 'middleware' => ['Auth']],
    '/admin/files/{id}/edit' => ['controller' => 'FileController', 'action' => 'edit', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/files/{id}/update' => ['controller' => 'FileController', 'action' => 'update', 'method' => 'POST', 'middleware' => ['Auth']],
    '/admin/files/{id}/delete' => ['controller' => 'FileController', 'action' => 'delete', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/files/{id}/toggle' => ['controller' => 'FileController', 'action' => 'toggleApproval', 'method' => 'GET', 'middleware' => ['Auth']],

    '/admin/users' => ['controller' => 'UserController', 'action' => 'index', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/users/create' => ['controller' => 'UserController', 'action' => 'create', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/users/store' => ['controller' => 'UserController', 'action' => 'store', 'method' => 'POST', 'middleware' => ['Auth']],
    '/admin/users/{id}/edit' => ['controller' => 'UserController', 'action' => 'edit', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/users/{id}/update' => ['controller' => 'UserController', 'action' => 'update', 'method' => 'POST', 'middleware' => ['Auth']],
    '/admin/users/{id}/delete' => ['controller' => 'UserController', 'action' => 'delete', 'method' => 'GET', 'middleware' => ['Auth']],

    '/admin/announcements' => ['controller' => 'AnnouncementController', 'action' => 'adminIndex', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/announcements/create' => ['controller' => 'AnnouncementController', 'action' => 'create', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/announcements/store' => ['controller' => 'AnnouncementController', 'action' => 'store', 'method' => 'POST', 'middleware' => ['Auth']],
    '/admin/announcements/{id}/edit' => ['controller' => 'AnnouncementController', 'action' => 'edit', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],
    '/admin/announcements/{id}/update' => ['controller' => 'AnnouncementController', 'action' => 'update', 'method' => 'POST', 'middleware' => ['Auth', 'Admin']],
    '/admin/announcements/{id}/delete' => ['controller' => 'AnnouncementController', 'action' => 'delete', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],

    '/admin/settings' => ['controller' => 'SettingController', 'action' => 'index', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],
    '/admin/settings/update' => ['controller' => 'SettingController', 'action' => 'update', 'method' => 'POST', 'middleware' => ['Auth', 'Admin']],

    '/admin/managers' => ['controller' => 'UserController', 'action' => 'index', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/managers/create' => ['controller' => 'UserController', 'action' => 'create', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/managers/store' => ['controller' => 'UserController', 'action' => 'store', 'method' => 'POST', 'middleware' => ['Auth']],
    '/admin/managers/{id}/edit' => ['controller' => 'UserController', 'action' => 'edit', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/managers/update' => ['controller' => 'UserController', 'action' => 'update', 'method' => 'POST', 'middleware' => ['Auth']],
    '/admin/managers/{id}/delete' => ['controller' => 'UserController', 'action' => 'delete', 'method' => 'GET', 'middleware' => ['Auth']],

    '/notifications/{id}/read' => ['controller' => 'NotificationController', 'action' => 'markRead', 'method' => 'POST', 'middleware' => ['Auth']],
    '/notifications/read-all' => ['controller' => 'NotificationController', 'action' => 'readAll', 'method' => 'POST', 'middleware' => ['Auth']],

    // مسارات API للتطبيق المحمول (Mobile Application API Endpoints)
    '/api/login' => ['controller' => 'ApiController', 'action' => 'login', 'method' => 'POST'],
    '/api/register' => ['controller' => 'ApiController', 'action' => 'register', 'method' => 'POST'],
    '/api/home' => ['controller' => 'ApiController', 'action' => 'home', 'method' => 'GET'],
    '/api/majors' => ['controller' => 'ApiController', 'action' => 'majors', 'method' => 'GET'],
    '/api/majors/{id}' => ['controller' => 'ApiController', 'action' => 'majorDetails', 'method' => 'GET'],
    '/api/courses/{id}' => ['controller' => 'ApiController', 'action' => 'courseDetails', 'method' => 'GET'],
    '/api/courses/{id}/rate' => ['controller' => 'ApiController', 'action' => 'rateCourse', 'method' => 'POST'],
    '/api/announcements' => ['controller' => 'ApiController', 'action' => 'announcements', 'method' => 'GET'],
    '/api/announcements/{id}' => ['controller' => 'ApiController', 'action' => 'announcementDetails', 'method' => 'GET'],
    '/api/search' => ['controller' => 'ApiController', 'action' => 'search', 'method' => 'GET'],
    '/api/files/{id}/download' => ['controller' => 'ApiController', 'action' => 'downloadFile', 'method' => 'GET'],
    '/api/request-role' => ['controller' => 'ApiController', 'action' => 'requestRole', 'method' => 'POST'],
    '/api/profile' => ['controller' => 'ApiController', 'action' => 'profile', 'method' => 'GET'],
    '/api/profile/update' => ['controller' => 'ApiController', 'action' => 'updateProfile', 'method' => 'POST'],
    '/api/settings' => ['controller' => 'ApiController', 'action' => 'settings', 'method' => 'GET'],
    '/api/about' => ['controller' => 'ApiController', 'action' => 'about', 'method' => 'GET'],
    '/api/contact' => ['controller' => 'ApiController', 'action' => 'contact', 'method' => 'GET'],
    '/api/admin/requests' => ['controller' => 'ApiController', 'action' => 'adminRequests', 'method' => 'GET'],
    '/api/admin/requests/{id}/approve' => ['controller' => 'ApiController', 'action' => 'approveRequest', 'method' => 'POST'],
    '/api/admin/requests/{id}/reject' => ['controller' => 'ApiController', 'action' => 'rejectRequest', 'method' => 'POST'],
    '/api/admin/stats' => ['controller' => 'ApiController', 'action' => 'adminStats', 'method' => 'GET'],
    '/api/admin/announcements/create' => ['controller' => 'ApiController', 'action' => 'createAnnouncement', 'method' => 'POST'],
    '/api/notifications' => ['controller' => 'ApiController', 'action' => 'notifications', 'method' => 'GET'],

    '/api/notifications/{id}/read' => ['controller' => 'ApiController', 'action' => 'markNotificationRead', 'method' => 'POST'],
    '/api/notifications/read-all' => ['controller' => 'ApiController', 'action' => 'markAllNotificationsRead', 'method' => 'POST'],
    '/api/bookmarks' => ['controller' => 'ApiController', 'action' => 'bookmarks', 'method' => 'GET'],
    '/api/bookmarks/toggle' => ['controller' => 'ApiController', 'action' => 'toggleBookmark', 'method' => 'POST'],

    // File upload & Admin management routes for Mobile App
    '/api/files/upload' => ['controller' => 'ApiController', 'action' => 'uploadFile', 'method' => 'POST'],
    '/api/admin/files' => ['controller' => 'ApiController', 'action' => 'adminFiles', 'method' => 'GET'],
    '/api/admin/files/{id}/approve' => ['controller' => 'ApiController', 'action' => 'approveFile', 'method' => 'POST'],
    '/api/admin/files/{id}/delete' => ['controller' => 'ApiController', 'action' => 'deleteFile', 'method' => 'POST'],
    '/api/admin/majors/create' => ['controller' => 'ApiController', 'action' => 'createMajor', 'method' => 'POST'],
    '/api/admin/majors/{id}/delete' => ['controller' => 'ApiController', 'action' => 'deleteMajor', 'method' => 'POST'],
    '/api/admin/courses' => ['controller' => 'ApiController', 'action' => 'adminCourses', 'method' => 'GET'],
    '/api/admin/courses/create' => ['controller' => 'ApiController', 'action' => 'createCourse', 'method' => 'POST'],
    '/api/admin/courses/{id}/delete' => ['controller' => 'ApiController', 'action' => 'deleteCourse', 'method' => 'POST'],
    '/api/admin/announcements/{id}/delete' => ['controller' => 'ApiController', 'action' => 'deleteAnnouncement', 'method' => 'POST'],
    '/api/admin/users' => ['controller' => 'ApiController', 'action' => 'adminUsers', 'method' => 'GET'],
    '/api/admin/users/{id}/role' => ['controller' => 'ApiController', 'action' => 'updateUserRole', 'method' => 'POST'],
];






