<?php

return [
    '/' => ['controller' => 'HomeController', 'action' => 'index', 'method' => 'GET'],
    '/home' => ['controller' => 'HomeController', 'action' => 'index', 'method' => 'GET'],
    '/courses/{id}' => ['controller' => 'CourseController', 'action' => 'show', 'method' => 'GET'],
    '/courses/{id}/files' => ['controller' => 'CourseController', 'action' => 'files', 'method' => 'GET'],
    '/courses/{id}/rate' => ['controller' => 'CourseController', 'action' => 'rate', 'method' => 'POST'],
    '/announcements' => ['controller' => 'AnnouncementController', 'action' => 'index', 'method' => 'GET'],
    '/announcements/{id}' => ['controller' => 'AnnouncementController', 'action' => 'show', 'method' => 'GET'],
    '/search' => ['controller' => 'SearchController', 'action' => 'index', 'method' => 'GET'],
    '/about' => ['controller' => 'PageController', 'action' => 'about', 'method' => 'GET'],
    '/contact' => ['controller' => 'PageController', 'action' => 'contact', 'method' => 'GET'],
    '/majors/{id}' => ['controller' => 'MajorController', 'action' => 'show', 'method' => 'GET'],
    '/files/{id}/download' => ['controller' => 'FileController', 'action' => 'download', 'method' => 'GET'],
    '/files/{id}/preview' => ['controller' => 'FileController', 'action' => 'preview', 'method' => 'GET'],

    '/login' => ['controller' => 'AuthController', 'action' => 'loginForm', 'method' => 'GET'],
    '/login/post' => ['controller' => 'AuthController', 'action' => 'login', 'method' => 'POST'],
    '/logout' => ['controller' => 'AuthController', 'action' => 'logout', 'method' => 'GET'],

    '/admin' => ['controller' => 'DashboardController', 'action' => 'index', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],
    '/admin/dashboard' => ['controller' => 'DashboardController', 'action' => 'index', 'method' => 'GET', 'middleware' => ['Auth']],

    '/admin/majors' => ['controller' => 'MajorController', 'action' => 'index', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/majors/create' => ['controller' => 'MajorController', 'action' => 'create', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],
    '/admin/majors/store' => ['controller' => 'MajorController', 'action' => 'store', 'method' => 'POST', 'middleware' => ['Auth', 'Admin']],
    '/admin/majors/{id}/edit' => ['controller' => 'MajorController', 'action' => 'edit', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],
    '/admin/majors/{id}/update' => ['controller' => 'MajorController', 'action' => 'update', 'method' => 'POST', 'middleware' => ['Auth', 'Admin']],
    '/admin/majors/{id}/delete' => ['controller' => 'MajorController', 'action' => 'delete', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],

    '/admin/levels' => ['controller' => 'LevelController', 'action' => 'index', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/levels/create' => ['controller' => 'LevelController', 'action' => 'create', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],
    '/admin/levels/store' => ['controller' => 'LevelController', 'action' => 'store', 'method' => 'POST', 'middleware' => ['Auth', 'Admin']],
    '/admin/levels/{id}/edit' => ['controller' => 'LevelController', 'action' => 'edit', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],
    '/admin/levels/{id}/update' => ['controller' => 'LevelController', 'action' => 'update', 'method' => 'POST', 'middleware' => ['Auth', 'Admin']],
'/admin/levels/{id}/delete' => ['controller' => 'LevelController', 'action' => 'delete', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],
    '/admin/semesters' => ['controller' => 'SemesterController', 'action' => 'index', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/semesters/create' => ['controller' => 'SemesterController', 'action' => 'create', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],
    '/admin/semesters/store' => ['controller' => 'SemesterController', 'action' => 'store', 'method' => 'POST', 'middleware' => ['Auth', 'Admin']],
    '/admin/semesters/{id}/edit' => ['controller' => 'SemesterController', 'action' => 'edit', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],
    '/admin/semesters/{id}/update' => ['controller' => 'SemesterController', 'action' => 'update', 'method' => 'POST', 'middleware' => ['Auth', 'Admin']],
    '/admin/semesters/{id}/delete' => ['controller' => 'SemesterController', 'action' => 'delete', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],

    '/admin/courses' => ['controller' => 'CourseController', 'action' => 'adminIndex', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/courses/create' => ['controller' => 'CourseController', 'action' => 'create', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/courses/store' => ['controller' => 'CourseController', 'action' => 'store', 'method' => 'POST', 'middleware' => ['Auth']],
    '/admin/courses/{id}/edit' => ['controller' => 'CourseController', 'action' => 'edit', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/courses/{id}/update' => ['controller' => 'CourseController', 'action' => 'update', 'method' => 'POST', 'middleware' => ['Auth']],
    '/admin/courses/{id}/delete' => ['controller' => 'CourseController', 'action' => 'delete', 'method' => 'GET', 'middleware' => ['Auth']],

    '/admin/files' => ['controller' => 'FileController', 'action' => 'index', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/files/create' => ['controller' => 'FileController', 'action' => 'create', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/files/store' => ['controller' => 'FileController', 'action' => 'store', 'method' => 'POST', 'middleware' => ['Auth']],
    '/admin/files/{id}/edit' => ['controller' => 'FileController', 'action' => 'edit', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/files/{id}/update' => ['controller' => 'FileController', 'action' => 'update', 'method' => 'POST', 'middleware' => ['Auth']],
    '/admin/files/{id}/delete' => ['controller' => 'FileController', 'action' => 'delete', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/files/{id}/toggle' => ['controller' => 'FileController', 'action' => 'toggleApproval', 'method' => 'GET', 'middleware' => ['Auth']],

    '/admin/users' => ['controller' => 'UserController', 'action' => 'index', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],
    '/admin/users/create' => ['controller' => 'UserController', 'action' => 'create', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],
    '/admin/users/store' => ['controller' => 'UserController', 'action' => 'store', 'method' => 'POST', 'middleware' => ['Auth', 'Admin']],
    '/admin/users/{id}/edit' => ['controller' => 'UserController', 'action' => 'edit', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],
    '/admin/users/{id}/update' => ['controller' => 'UserController', 'action' => 'update', 'method' => 'POST', 'middleware' => ['Auth', 'Admin']],
    '/admin/users/{id}/delete' => ['controller' => 'UserController', 'action' => 'delete', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],

    '/admin/announcements' => ['controller' => 'AnnouncementController', 'action' => 'adminIndex', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/announcements/create' => ['controller' => 'AnnouncementController', 'action' => 'create', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/announcements/store' => ['controller' => 'AnnouncementController', 'action' => 'store', 'method' => 'POST', 'middleware' => ['Auth']],
    '/admin/announcements/{id}/edit' => ['controller' => 'AnnouncementController', 'action' => 'edit', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],
    '/admin/announcements/{id}/update' => ['controller' => 'AnnouncementController', 'action' => 'update', 'method' => 'POST', 'middleware' => ['Auth', 'Admin']],
    '/admin/announcements/{id}/delete' => ['controller' => 'AnnouncementController', 'action' => 'delete', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],

    '/admin/settings' => ['controller' => 'SettingController', 'action' => 'index', 'method' => 'GET', 'middleware' => ['Auth', 'Admin']],
    '/admin/settings/update' => ['controller' => 'SettingController', 'action' => 'update', 'method' => 'POST', 'middleware' => ['Auth', 'Admin']],

    '/admin/managers' => ['controller' => 'ManagerController', 'action' => 'index', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/managers/create' => ['controller' => 'ManagerController', 'action' => 'create', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/managers/store' => ['controller' => 'ManagerController', 'action' => 'store', 'method' => 'POST', 'middleware' => ['Auth']],
    '/admin/managers/{id}/edit' => ['controller' => 'ManagerController', 'action' => 'edit', 'method' => 'GET', 'middleware' => ['Auth']],
    '/admin/managers/update' => ['controller' => 'ManagerController', 'action' => 'update', 'method' => 'POST', 'middleware' => ['Auth']],
    '/admin/managers/{id}/delete' => ['controller' => 'ManagerController', 'action' => 'delete', 'method' => 'GET', 'middleware' => ['Auth']],
];
